### ISSUE TITLE
add decoding="async" attribute to all img

### ISSUE THREAD

**Issue by Ethermine-pool** [gildesmarais/jekyll-loading-lazy#11]
Hello,
How can add decoding=“async” attribute to all img?
example:
<img decoding="async" src="/img.jpg" alt="">

It would be great to implement this in a plugin.

**Comment by gildesmarais** [comment]
Hi,

thank you for bringing attention to `decoding="async"` (for anyone interested, here's the MDN: [`HTMLImageElement.decoding`
](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decoding)).

I agree, it should be implemented in a plugin. It should be a plugin on its own as it does not fit into jekyll-loading-lazy's scope.

I recommend taking the way [described on the Jekyll Forum](https://talk.jekyllrb.com/t/how-can-i-add-decoding-async-attribute-to-all-img/5590) to achieve this.

Cheers!
